language: java
dist: trusty
sudo: require
services:
- docker

env:
  global:
  - secure: L1TVr/R9ZeMI3bW2nx/yZQBKqFapjyCjRQo8KTcqlKOKLu5btWGYROqsH7tVAjocPhW8FzzD2SJCGe/RG1TFwjDYpU6OZsApUYO0hUfEng94lOApLq4Irnjny369wOEiJ+9kpLJs2dV2x6tXl1jQnzgsrcTueepFxqU8engX2FZ/7+slm9IPC14Y+6cJfvrE5Wq4ZNCa3fucCxPLH5SfNI94AaPvOeHW5p/DlsMaF3x3Due+nMw7YfUBcgitNCrM92lqUVcmsWm0XKdi2AoXiIp+TdPfyFi0fnqOR5+TWTMqxV2fTUmHRUUhlM2U1jKt4l7UeAJsDhRXZj/92N3dP0hTNvhCN5oF6gBt5rou2AXQRCG3FG36odRUoLvJrPs4poKgMMffGcPogU/ToS8KKG3zUIgf6iYkO6fedkfGAiisLRI7UGp2vZip9XbajmbZsxWVyGKzP9qT5tQeCTaJvPD0w9KJ8C+aaAMvdlUYlhCM0YmW7NiurvVQbQD0NzcYkMn3nnK20zduPe6/Gpp6s6jHQcHzO260JU2yR1FttSSBuAQNDm7EBBBxYHebdXpdKWaBWp1+JNLnvV60Mmq4ROy5giuHlBFBAlcogks/dqHQKN/mxD/jMYOpUzsqP9MD8xm1D/nH6toZqhGIKcqZLFDY+APsAg6tYcsWH7qBdP4=
  - secure: QXKPP7+Ktit/LtBCV27vbPhAB6DLfbhMIfnn2D92wT9XJXOqvwg9EafdDCusQp9aJoWePPS60y4NE/vqfWVIfPxcFfmQHkdtGH6YzPU1bfpbzMv7Tr/DtUhw3uviFzd5pOlusq6gtsAgBbYjTAK0RSTZPSDST1N2m/HTTLTlmCyNfVtdjdaAYyz6J0M6EtSEKvwSqYMW9JHVqHJroO7VS9X/Pyj9/Wocvxl5s4pfYofr0wGRG7zxxZ5dVRikatxuIvDhGyYydhYEG8XJ5a2RuuNKTj8qrAC6kus+lIASFrN/FEgPUO8K/BwMoBrS5R8EjQeLRT2FuUl86oiJ/YXdi/wDl+L5KspDWxOfUwxbCVIFbqi9BdGDBnWHl6N1pcKmW+pe5mcu2gzcEdOgZJCjgAkoKno/nhE2ew77KRqjOeh5SRPqLO1KMtxt7Ixos+ZIAFxookARF7UO0rydbBLOF5D2mBP/SP8E5r6xivTSOrovd34l0juUKMggudMmD1OmAcmp0qFqQSnQghx/dAw5B1oOMlv6qw9i85tW9xEImpuFacNTal05tGPCreb6N2FVg5qLw0toJSD+2gQRxXqhFbgD//HvEhsGAWc/anhg+2PQTSwSEeUoccBD/5FC6SjecZmQ6Pzyq64nYckbGYo/92zWO520VoZzjGq6UEvrbKo=


before_install:
- docker build -t seo80/seo80-docker-repo .

script:
- docker run --rm seo80/seo80-docker-repo ./gradlew clean jar

stages:
- coverage
- deploy
jobs:
  include:
  - stage: coverage
    name: Coverage ui-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.5
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/ui check"
  - stage: coverage
    name: Coverage service-cart-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.5
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/service/cart
      check"
  - stage: coverage
    name: Coverage service-user-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.5
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/service/user
      check"
  - stage: coverage
    name: Coverage order-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.24
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/repository/order
      check"
  - stage: coverage
    name: Coverage repository-cart-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.5
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/repository/cart
      check"
  - stage: coverage
    name: Coverage product-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.5
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/repository/product
      check"
  - stage: coverage
    name: Coverage repositort-user-check JAVA 8
    intall: skip
    script:
    - docker run --rm seo80/seo80-docker-repo /bin/bash -c "$GRADLE_CHECK"
    env:
    - JDK_USED=8
    - COVERAGE_VALUE=0.24
    - GRADLE_CHECK="COVERAGE=$COVERAGE_VALUE ./gradlew -p ./monolithic/repository/user
      check"
  - stage: deploy
    name: Deploy JAVA 8
    install: skip
    script: skip
    deploy:
      provider: script
      script: "./scripts/deploy.sh"
      on:
        branch: master
